---
title: "EwE North Sea 2020"
author: "Erik Olsen"
date: "9/30/2020"
output: html_document
---

# Scenario analysis, North Sea  using Ecopath with Ecosim
Mackinson et al 2016 model

### Libraries
```{r libraries, echo=FALSE, warning=FALSE}
library(tidyr)
library(readxl)
library(ggplot2)
library(data.table)
library(dplyr)
library(kableExtra)
```

## Import data
### Kattegat
```{r import data, echo=FALSE, warning=FALSE}
#biomass groups 
gr <- read.table("./data/NS_EwE/NAMES_GRPS.csv", sep=",", header=TRUE)


catlist<-list.files("./data/NS_EwE/")[1:5]
scenarios <- c("baseline", "No fishing", "-50%  fishing", "+25%  fishing", "+75%  fishing")


#BIOMASS DATA
#biomass baseline
#b_base <- read.table(paste("./", catlist[1], "/biomass_annual.csv", sep=""), header=TRUE, dec=".", sep =",",skip=8)
#b_base$scenario <- c("baseline")

# biomass scenarios
bscen <- c("b_base", "b_f0", "b_btm50", "b_btp25", "b_btp75")

for (i in 1:length(catlist)) { 
  cc1 <- read.table(paste("./data/NS_EwE/", catlist[i], "/biomass_annual.csv", sep=""), header=TRUE, dec=".", sep =",",skip=8)
  colnames(cc1) <- c("year", gr$NAM)
  cc1$scenario <- c(scenarios[i])
  #cc1$norm <- cc1$value/c_base$value
  assign(bscen[i], cc1)
}

#biomass normalized & long-format
b_norm <- cbind(b_base$year, b_f0$scenario, b_f0[,2:70]/b_base[,2:70])
colnames(b_norm) <- c("year", "scenario", colnames(b_base[,2:70]))
slist <- list(b_btm50, b_btp25, b_btp75)

for (i in 1:3) {  
  bb <- cbind(as.data.frame(slist[i])$year, as.data.frame(slist[i])$scenario, as.data.frame(slist[i])[,2:70]/b_base[,2:70]) 
  colnames(bb) <- c("year", "scenario", colnames(b_base[,2:70]))
  b_norm <- rbind(b_norm, bb)
  }




#CATCH DATA
#catch baseline
#c_base <- read.table(paste("./", catlist[1], "/Catch_annual.csv", sep=""), header=TRUE, dec=".", sep =",",skip=8)
#c_base$scenario <- c("baseline")

# catch scenarios
cscen <- c("c_base", "c_f0", "c_btm50", "c_btp25", "c_btp75")

for (i in 1:length(catlist)) { 
  cc1 <- read.table(paste("./data/NS_EwE/", catlist[i], "/Catch_annual.csv", sep=""), header=TRUE, dec=".", sep =",",skip=8)
  #colnames(cc1) <- c("year", "fleet", "group", "value")
  cc1$scenario <- c(scenarios[i])
  #cc1$norm <- cc1$value/c_base$value
  assign(cscen[i], cc1)
}

#Fill inn with 0-catches for 'no-catch' scenario
#c_base$id <- paste(c_base$year, c_base$fleet, c_base$group, sep="")
#c_f0$id <- paste(c_f0$year, c_f0$fleet, c_f0$group, sep="")
#c_base$f0 <- 0
#c_base$f0 <- c_f0$value[match(c_base$id, c_f0$id)]
#c_f0a <- c_base[,c(1,2,3,7,5)]
#colnames(c_f0a)[4] <- c("value")
#c_f0a$scenario <- c("No fishing")


# catch normalized
#c_f0$norm <- c_f0a$value/c_base$value 
#c_btm50$norm <- c_btm50$value/c_base$value 
#c_btp25$norm <- c_btp25$value/c_base$value 
#c_btp75$norm <- c_btp75$value/c_base$value 
#c_sx2$norm <- c_sx2$value/c_base$value 
#c_sx10$norm <- c_sx10$value/c_base$value 

#catch normalized combined long form data
#c_all <- rbind(c_f0a, c_btm50, c_btp25, c_btp75, c_sx2, c_sx10)
#c_all$fleet_n <- fleets$name[match(c_all$fleet, fleets$gr)]
#c_all$group_n <- gr$name[match(c_all$group, gr$gr)]



#catch normalized & long-format
c_norm <- cbind(c_base$Year, c_f0$scenario, c_f0[,2:70]/c_base[,2:70])
colnames(c_norm) <- c("year", "scenario", colnames(c_base[,2:70]))
slist <- list(c_btm50, c_btp25, c_btp75)

for (i in 1:3) {  
  bb <- cbind(as.data.frame(slist[i])$Year, as.data.frame(slist[i])$scenario, as.data.frame(slist[i])[,2:70]/c_base[,2:70]) 
  colnames(bb) <- c("year", "scenario", colnames(c_base[,2:70]))
  c_norm <- rbind(c_norm, bb)
  }



```

## Biomass time-series plots

```{r biomass plots, echo=FALSE, warning=FALSE}

b_norm.long <-b_norm %>% gather(Species, Value, -year, -scenario)

biom.plot <- ggplot(b_norm.long, aes(year, Value, color=scenario))
biom.plot + geom_line() + facet_wrap(~Species, scales="free_y") + theme_bw() + ggtitle("Biomass of species groups")
ggsave("./figs/NS biomass species groups.png", width=16, height=8)

```


## Catch time series plots
```{r catch plots, echo=FALSE, warning=FALSE}
catch_long <- c_norm %>% gather(Species, Value, -year, -scenario)
  
  
catch.plot <- ggplot(catch_long, aes(year, Value, color=scenario))
catch.plot + geom_line() + facet_wrap(~Species, scales="free_y") + theme_bw() + ggtitle("Catch by species groups and fleets")
ggsave("./figs/NS catch groups fleets.png", width=16, height=8)
```



## Average change over time series (since 2019)
### Biomass
```{r biomass change table, echo=FALSE, warning=FALSE}
b_norm <- data.table(b_norm)

b_average <- b_norm[year>2019, lapply(.SD, mean), by = .(scenario), .SDcols = 3:71]

b_average <- data.table::transpose(b_average, keep.names="rn")
colnames(b_average) <- as.character(b_average[1,])
b_average <- b_average[scenario!="scenario",]
write.csv(b_average, "./figs/biomass NS.csv")
b_average %>% 
  kable(format = "html", escape = F, rownames=TRUE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) 
```
### Catches
```{r catch changes over time table, echo=FALSE, warning=FALSE}
c_norm <- data.table(c_norm)

c_average <- c_norm[year>2019, lapply(.SD, mean), by = .(scenario), .SDcols = 3:71] 
#%>% select_if(~sum(!is.na(.)) > 0)

c_average <- data.table::transpose(c_average, keep.names="rn")
colnames(c_average) <- as.character(c_average[1,])
c_average <- c_average[scenario!="scenario",]
write.csv(c_average, "./figs/catch NS.csv")
c_average %>% 
  kable(format = "html", escape = F, rownames=TRUE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) 
```


